### ISSUE TITLE
Bump the OpenTelemetry family together and migrate telemetry.rs to the 0.32 SDK API

### ISSUE THREAD

**Issue by ELares** [ELares/IronAuth#456]
Dependabot PR #307 was closed in favour of this issue. It bumped **one line of four** and cannot be green on its own, so it would be refiled forever.

## Why the PR could not work

`Cargo.toml` (around :249-252) declares four crates as a family: `opentelemetry`, `opentelemetry_sdk`, `opentelemetry-otlp`, `tracing-opentelemetry`. Dependabot moved only the first. Measured as filed:

```
error[E0599]: no method named `tracer` found for struct `opentelemetry_sdk::trace::TracerProvider`
  --> crates/ironauth-server/src/telemetry.rs:207:31
note: there are multiple different versions of crate `opentelemetry` in the dependency graph
```

Two `opentelemetry` versions coexist and the 0.27 SDK does not implement the 0.32 trait.

## The correct bump also needs code changes

Measured with the whole family moved (opentelemetry 0.32, opentelemetry_sdk 0.32, opentelemetry-otlp 0.32, tracing-opentelemetry 0.33, that pairing verified against the crates.io dependency API):

```
error[E0432]: unresolved import `opentelemetry_sdk::trace::TracerProvider`
  --> crates/ironauth-server/src/telemetry.rs:176:9
  help: a similar name exists: SdkTracerProvider
error[E0425]: cannot find type `TracerProvider` in module `opentelemetry_sdk::trace`
  --> crates/ironauth-server/src/telemetry.rs:35:44
```

Affected call sites, all in `crates/ironauth-server/src/telemetry.rs`:

- :35 the `TelemetryGuard.otel` field type
- :175 `use opentelemetry_sdk::runtime::Tokio`
- :176 the import
- :205 `TracerProvider::builder()`
- :206 `.with_batch_exporter(exporter, Tokio)`, whose runtime argument was dropped upstream
- :43 `provider.shutdown()`

**Compilation halts at name resolution, so these two errors are a floor, not the total.** More will surface once the rename is done.

## Scope

Roughly half a day, plus a real reachability check: `otlp` is a **non-default feature** exercised only by the `--all-features` lanes, so a change here is easy to break without noticing locally.

MSRV is not a constraint: opentelemetry 0.32.0 declares `rust-version = 1.75.0`, well under the 1.85 floor.

**Comment by ELares** [comment]
Shipped in PR #553. All four crates moved together: `opentelemetry` 0.32, `opentelemetry_sdk` 0.32, `opentelemetry-otlp` 0.32, `tracing-opentelemetry` 0.33, exactly the pairing this issue verified.

The three call sites were each a rename or signature change: `TracerProvider` became `SdkTracerProvider` (the rename frees the plain name for the API TRAIT `.tracer()` comes from, which this module already imported separately, so the two no longer collide); `with_batch_exporter` lost its runtime argument because the SDK owns its batch worker now, which is why `opentelemetry_sdk::runtime::Tokio` is gone from the imports rather than merely unused; and `shutdown()` changed its return type, which the guard's `Drop` swallows either way.

**The reachability warning in this issue was the important part, and it was worse than stated.** Nothing exercised `otlp::build` AT ALL before this, so the whole path was compile-verified only. For a migration that renamed a type, dropped an argument and changed a return type, the existing tests would have noticed none of it. Two tests now cover it: the inert no-endpoint half, and a configured endpoint that CONSTRUCTS the exporter, the `SdkTracerProvider`, its batch worker and the `tracing-opentelemetry` layer and then drives `shutdown()`. No collector needs to be listening, since the tonic exporter connects lazily.

Mutation note worth recording: my first attempt did not COMPILE, which proves nothing about a test, so it was redone as two that build. A configured endpoint silently yielding no exporter (export quietly disabled), and the provider built but not returned (pending spans lost at exit). Each fails the live test.

The bump also moves `tonic` 0.12 to 0.14 and drops a `tower` 0.4 from the graph; `cargo deny check` is clean on advisories, bans, licenses and sources. MSRV was never a constraint (0.32 declares 1.75.0, under the 1.85 floor).

Dependabot #307 stays closed: it moved one line of four and could not have been green.
